#https://developers.google.com/appengine/docs/python/config/appconfig
application: opendoor-1070
module: default
version: 1-0-0
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "10m"
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots\.txt

#https://developers.google.com/appengine/articles/python/recording_exceptions_with_ereporter
- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"

#https://developers.google.com/appengine/docs/python/tools/appstats?csw=1
builtins:
- appstats: on
- remote_api: on
- deferred: on
